import { Inter } from "next/font/google";
import "./globals.css";
import Navbar from '../Components/Navbar/Navbar';
import AuthProvider from './../../context/AuthContext';
import Footer from '../Components/Footer/Footer';
import HeroSection from './../Components/HeroSection';

const inter = Inter({ subsets: ["latin"] });

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <AuthProvider>
        <body className={inter.className}>
          <Navbar />
          <HeroSection />
          {children}
          <Footer />  {/* na place this footer get for always be. i.e inside the body */}
        </body>
      </AuthProvider>
    </html>
  );
}